directories:
  output: release
  buildResources: build
appId: com.gestor.app
productName: GestorPro
files:
  - filter:
      - dist/**/*
      - main.js
      - package.json
extraResources:
  - from: Backend/publish
    to: Backend/publish
win:
  target: nsis
nsis:
  oneClick: true
  perMachine: false
  allowToChangeInstallationDirectory: false
electronVersion: 41.2.1
